### ISSUE TITLE
NPM Error

### ISSUE THREAD

**Issue by northerchild** [creotip/vue-particles#27]
Hi guys i have this problem 
./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-particles/src/vue-particles/vue-particles.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "C:\\Users\\USUARIO\\Desktop\\Lenguajes\\Vue.js\\VueTask\\norther-task\\node_modules\\vue-particles\\.babelrc" at 0, attempted to resolve relative to "C:\\Users\\USUARIO\\Desktop\\Lenguajes\\Vue.js\\VueTask\\norther-task\\node_modules\\vue-particles"
    at C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (C:\Users\USUARIO\Desktop\Lenguajes\Vue.js\VueTask\norther-task\node_modules\babel-loader\lib\index.js:175:20)
 @ ./node_modules/vue-particles/src/vue-particles/vue-particles.vue 4:0-103 5:0-116
 @ ./node_modules/vue-particles/src/vue-particles/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by leo91000** [comment]
Same here

**Comment by gaceladri** [comment]
Same.

I started with the vue-hackernews-2.0, I did npm install vue-particles --save & npm install vue-particles --save-dev after when it didnt work.

`ERROR in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/vue-particles/src/vue-particles/vue-particles.vue
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in ".../webapp/vue-hackernews-2.0/node_modules/vue-particles/.babelrc" at 0, attempted to resolve relative to ".../webapp/vue-hackernews-2.0/node_modules/vue-particles"
    at .../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (.../webapp/vue-hackernews-2.0/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (.../webapp/vue-hackernews-2.0/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (.../webapp/vue-hackernews-2.0/node_modules/babel-loader/lib/index.js:175:20)
 @ ./node_modules/vue-particles/src/vue-particles/vue-particles.vue 4:0-126
 @ ./node_modules/vue-particles/src/vue-particles/index.js
 @ ./src/entry-client.js
 @ multi webpack-hot-middleware/client ./src/entry-client.js
`

**EDIT** as seen in https://github.com/creotip/vue-particles/issues/1 the error seems to be fixed with: 
npm install babel-plugin-transform-runtime --save
npm install babel-preset-stage-2 --save

@leo91000 @northerchild

**Comment by northerchild** [comment]
Guys you can solve this problem? @leo91000  @gaceladri

**Comment by raideer** [comment]
Running `npm install babel-plugin-transform-runtime babel-preset-stage-2 --save-dev` fixed the problem for me

**Comment by northerchild** [comment]
Ok thanks mr @raideer

**Comment by agtoncerqueira** [comment]
Solved to me either!
