### ISSUE TITLE
Doesn't work with SSR

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [creotip/vue-particles#4]
Please, consider making an edit to your README.md
It doesn't work with SSR, also tested with nuxt.
The following **doesn't work:**
```
plugins: [ '~plugins/vue-particles` ]
```
error:
```
Nuxt.js Error:
/nuxt-website/node_modules/vue-particles/src/vue-particles/index.js:2
import particles from './vue-particles.vue'
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/nuxt-website/node_modules/vue-server-renderer/build.js:6964:16)
    at Object.<anonymous> (webpack:/external "vue-particles":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap de794b84f45fea3bc548:25:0)
    at Object.module.exports.Object.defineProperty.value (server-bundle.js:2066:72)
    at __webpack_require__ (webpack:/webpack/bootstrap de794b84f45fea3bc548:25:0)
    at Object.module.exports.module.exports.list (.nuxt/index.js:83:0)
    at __webpack_require__ (webpack:/webpack/bootstrap de794b84f45fea3bc548:25:0)
```

However, it passes when `ssr: false` is set:
```
plugins: [
    { src: '~plugins/vue-particles`, ssr: false }
]
```
But doesn't work anyway.
File `~plugins/vue-particles`:
```
import Vue from 'vue'
import VueParticles from 'vue-particles'

Vue.use(VueParticles);
```
Using created `vue-particles` component inside `~pages/index.vue`:
```
<template lang='pug'>
.home
    vue-particles(color="#ffffff", :particleOpacity="0.7",
        linesColor="#ffffff",
        :particlesNumber="80",
        shapeType="circle",
        :particleSize="5",
        :linesWidth="2",
        :lineLinked="true",
        :lineOpacity="0.4",
        :linesDistance="150",
        :moveSpeed="3",
        :hoverEffect="true",
        hoverMode="grab",
        :clickEffect="true",
        clickMode="push"
        )
</template>
```
Then, gives the following error associated with the different SSR and client-side:
![screenshot_20170508_21_06_31](https://cloud.githubusercontent.com/assets/9992724/25810597/61787a8e-3432-11e7-8de5-4c32595fed5c.png)

The project is has no components in `~components` folder and a single page component, which is `~pages/index.vue`.
Here is a list of dependencies `package.json`
```
  "dependencies": {
    "nuxt": "latest",
    "axios": "^0.16.1"
  },
  "devDependencies": {
    "vue-particles": "^1.0.5",
    "node-sass": "^4.5.0",
    "pug": "^2.0.0-beta9",
    "pug-loader": "^2.3.0",
    "sass-loader": "^6.0.3"
  }
```

**Comment by OlzhasAlexandrov** [comment]
Works if set as a **devDependency**, but doesn't if set as a `dependency`

**Comment by creotip** [comment]
@OlzhasAlexandrov 
Thanks for pointing that out!

**Comment by ezamelczyk** [comment]
Why is this issue closed? It still doesn't work. Even when set as devDependency

**Comment by renztoygwapo** [comment]
any updates on this ? still not working even in devDependency.

**Comment by andrew-frank** [comment]
I had the same issue with Nuxt – `vue-particles` caused SSR to fail:

```
The client-side rendered virtual DOM tree is not matching server-rendered content. 
This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. 
Bailing hydration and performing full client-side render.
```

My solution was to wrap `<vue-particles/>` inside a `<no-ssr>` component from Nuxt! 
Docs: https://nuxtjs.org/api/components-no-ssr/
