### ISSUE TITLE
Error running on Nuxt generating on static file.

### ISSUE THREAD

**Issue by mpatino117** [creotip/vue-particles#5]
Project/packages does work, while running under development local environment. However, crashes under production and or [static generated files](https://nuxtjs.org/guide/#static-generated).

Here I am getting:

ERROR in 2.nuxt.bundle.a209f5cd138dc09bbe9d.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/vue-particles/src/vue-particles/index.js:6,0][2.nuxt.bundle.a209f5cd138dc09bbe9d.js:1998,12]
Error: Webpack build exited with errors
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\nuxt\dist\nuxt.js:905:44
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:272:15
    at Compiler.emitRecords (C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:367:37)
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:265:12
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:360:11
    at next (C:\Users\mpati\Desktop\insurance-scanner\node_modules\tapable\lib\Tapable.js:154:11)
    at Compiler.compiler.plugin (C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (C:\Users\mpati\Desktop\insurance-scanner\node_modules\tapable\lib\Tapable.js:158:13)
    at Compiler.afterEmit (C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:357:8)
    at Compiler.<anonymous> (C:\Users\mpati\Desktop\insurance-scanner\node_modules\webpack\lib\Compiler.js:352:14)
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\async\dist\async.js:421:16
    at iteratorCallback (C:\Users\mpati\Desktop\insurance-scanner\node_modules\async\dist\async.js:998:13)
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\async\dist\async.js:906:16
    at C:\Users\mpati\Desktop\insurance-scanner\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "generate"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! insurance-ui@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the insurance-ui@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the insurance-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs insurance-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls insurance-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\mpati\Desktop\insurance-scanner\npm-debug.log

**Comment by roslaneshellanoo** [comment]
@mpatino117 @Atinux 
I checked this out.
The problem is that if i'm just importing empty component , it gives me errors

Tagged @Atinux  , May be he will help!

**Comment by Atinux** [comment]
@mpatino117 please create a reproduction repository otherwise the community cannot help you by guessing.

I'll re-open this issue when a reproduction link will be given (fork of https://glitch.com/edit/#!/nuxt-hello-world or a Github repository)

**Comment by creotip** [comment]
@Atinux 
Published the latest version

**Comment by leyume** [comment]
Hello...
Still have the same problem in Production (though it works well in Dev)

ERROR in nuxt.bundle.cbc0aa4895848c4ffe9e.js from UglifyJs
Unexpected token: punc (() [./~/vue-particles/src/vue-particles/index.js:6,0][nuxt.bundle.cbc0aa4895848c4ffe9e.js:11071,12]
Error: Webpack build exited with errors

Please how do we resolve this?

**Comment by mpatino117** [comment]
Thank you!!

**Comment by leyume** [comment]
After several hours of debugging... was able to find a solution ... Not a good practice to modify node_modules files but resolves the problem. I will like to know why it works...

in the file - /~/vue-particles/src/vue-particles/index.js

Changed

```
/* eslint-disable */
import particles from './vue-particles.vue'

const VueParticles = {

    install (Vue, options) {
        Vue.component('vue-particles', particles)
    }

}

export default VueParticles
/* eslint-disable */
```

to

```
/* eslint-disable */
import particles from './vue-particles.vue'

const VueParticles = {

    install: function (Vue, options) {
        Vue.component('vue-particles', particles)
    }

}

export default VueParticles
/* eslint-disable */
```
